feat(Sidebar): add new component
Elonsoft/elonkit-react pull request #105
Opened 2022-06-21 13:52 UTC by va25j

2022-06-21 15:01 UTC, feerzlay requested changes

2022-06-21 15:01 UTC, feerzlay commented on src/components/Sidebar/SidebarToggle/SidebarToggle.tsx
> +      <SidebarToggleButton
Раз это иконочная кнопка, то ей еще нужен `aria-label`.

2022-07-18 14:03 UTC, feerzlay requested changes

2022-07-18 14:03 UTC, feerzlay commented on src/components/Sidenav/index.ts
> +export { SidenavProps } from './Sidenav.types';
Добавить экспорт из `SedenavItem` (и поправить имя папки)

2022-07-18 14:03 UTC, feerzlay commented on src/components/Sidenav/Sidenav.context.tsx
> +    throw new Error('Not provider for SidenavContext');
```suggestion
    throw new Error('No provider for SidenavContext.');
```

2022-07-19 12:50 UTC, feerzlay requested changes

2022-07-19 12:50 UTC, feerzlay commented on src/components/Sidebar/SidebarScrollable/SidebarScrollable.tsx
> +  const SidebarScrollableRef = useRef<HTMLDivElement | null>(null);
Можно просто
```suggestion
  const ref = useRef<HTMLDivElement | null>(null);
```

2022-07-19 12:50 UTC, feerzlay commented on src/components/Sidenav/index.ts
> +export { SidenavItem } from './SidenavItem';
Для подкомпонентов нужно экспортить все что есть
```suggestion
export * from './SidenavItem';
```

2022-07-19 12:50 UTC, feerzlay commented on src/components/index.ts
> +export * from './Sidebar';
Добавить экспорт `Sidenav`

2022-07-21 14:23 UTC, feerzlay requested changes

2022-07-21 14:23 UTC, feerzlay commented on src/components/Sidebar/SidebarItem/SidebarItem.types.ts
> +  component?: ElementType;
Это делается хитрее, посмотри компонент ссылки. Более того, надо использовать в самом компоненте потом.

2022-07-21 14:23 UTC, feerzlay commented on src/components/Sidebar/SidebarItem/SidebarItem.tsx
> +  return (
Много лишних тернарников.
1. Тултип делаем всегда, вне зависимости от open или children, но по open его дизейблить.
2. Условный рендер дочерних элементов нужно делать непосредсвенно для самого меню, а не заново весь родительский пункт меню описывать.

В общем тут в рендере кода должно быть раза в 4 меньше =)

2022-07-21 14:23 UTC, feerzlay commented on src/components/Sidebar/SidebarItem/SidebarItem.tsx
> +                <SidebarItemMenuItem className={clsx(classes.itemMenuItem, className)} key={idx}>
Нужно заспредить пропсы из оригинального пункта меню, потому что, например, туда будут пробрасываться `component="a"` и `href="..."`

2022-07-21 14:23 UTC, feerzlay commented on src/components/Sidebar/SidebarItem/SidebarItem.tsx
> +    overflow: 'auto'
Использовать overlay скроллбар

2022-07-21 14:23 UTC, feerzlay commented on src/components/Sidebar/SidebarItem/SidebarItem.tsx
> +        <SidebarItemTooltip
Нужно проработать момент, что когда в тултипе есть подпункты, то по тапу должен появляться тултип.

2022-07-21 14:23 UTC, feerzlay commented on src/components/Sidebar/SidebarMenu/SidebarMenu.types.ts
> +  behaviour?: 'click' | 'hover';
Подвязать эту логику и добавить контрол в демку.

2022-07-21 14:23 UTC, feerzlay commented on src/components/Sidebar/Sidebar.stories.tsx
> +          <SidebarItem icon={<Icon>bookmark</Icon>} text="Bookmarks" component="div">
Не хватает id

2022-07-25 08:09 UTC, feerzlay requested changes

2022-07-25 08:09 UTC, feerzlay commented on src/components/Sidebar/SidebarItem/SidebarItem.tsx
> +                    <SidebarItemMenuItem className={clsx(classes.itemMenuItem, className)} key={idx} {...props}>
Это пропсы родительского пункта меню, а не его подпункта =) Так у тебя получится что, например, у родителя и всех пунков меню будет одинаковая ссылка.
Нужно использовать `child.props`

2022-07-25 08:09 UTC, feerzlay commented on src/components/Sidebar/SidebarItem/SidebarItem.tsx
> +    color: theme.palette.monoB[500]
Цвет должен задаваться у какого-то дочернего элемента, иначе это сломает скроллбар.

2022-07-25 08:09 UTC, feerzlay commented on src/components/Sidebar/SidebarItem/SidebarItem.tsx
> +        leaveTouchDelay={2000}
Хорошо бы сделать чтобы по тапу сразу открывался. Для этого у тултипа нужно сделать контролируемое состояние `open` и как-то через `onTouchStart` (или `onPointerDown`) и `onClick` отслеживать пат и изменять состояние `open`.

2022-07-26 11:10 UTC, feerzlay commented on src/components/Sidebar/Sidebar.stories.tsx
> +        <SidebarScrollable afterScroll={<SidebarDivider />}>
Давай на все `SidebarItem` внутри этого скролла добавим `onClick={() => console.log(сюда название пункта меню)}`
Чтобы в дальнейшем можно было тестить правильное ли поведение при клике

2022-08-03 15:19 UTC, feerzlay requested changes

2022-08-03 15:19 UTC, feerzlay commented on src/components/Sidebar/Sidebar.tsx
> +  const onMouseMoveLatest = useLatest(() => {
По логике это же
```suggestion
  const onWidthChangeLatest = useLatest(() => {
```

2022-08-03 15:19 UTC, feerzlay commented on src/components/Sidebar/Sidebar.tsx
> +  const onResizeCommit = (event: MouseEvent) => {
Содержимое этой функции можно прям в обработчик где она вызывается засунуть, нет особой нужды выносить. Тем более название неправильное =)

2022-11-09 09:50 UTC, feerzlay requested changes

2022-11-09 09:50 UTC, feerzlay commented on src/components/Sidebar/SidebarItem/SidebarItem.classes.ts
> +  itemButton: string;
Поубирать префиксы `item`.

2022-11-09 09:50 UTC, feerzlay commented on src/components/Sidebar/Sidebar.stories.tsx
> +              text="Projects"
Добавить возможность отображения демки с русскими текстами.

2022-11-09 09:50 UTC, feerzlay commented on src/components/Sidebar/SidebarItem/SidebarItem.tsx
> +                    <IconChevronLeftMedium />
Вынести в пропс `iconToggle`.

2022-11-09 09:50 UTC, feerzlay commented on src/components/Sidebar/SidebarItem/SidebarItem.tsx
> +                size="24"
Добавить `aria-label`.

2022-11-09 09:50 UTC, feerzlay commented on src/components/Sidebar/SidebarItem/SidebarItem.tsx
> +  useEffect(() => {
За шириной нужно следить через resize observer. Увидишь проблему, когда переключение языка в демке прикрутишь.

2022-11-09 09:50 UTC, feerzlay commented on src/components/Sidebar/SidebarItem/SidebarItem.tsx
> +  const [left, setLeft] = useState<number>(0);
```suggestion
  const [width, setWidth] = useState<number>(0);
```

2022-11-09 09:50 UTC, feerzlay commented on src/components/Sidebar/SidebarItem/SidebarItem.tsx
> +const SidebarItemMenuItem = styled(MenuItem, {
```suggestion
const SidebarItemTooltipItem = styled(MenuItem, {
```
Так очевиднее будет

2022-11-09 09:50 UTC, feerzlay commented on src/components/Sidebar/SidebarItem/SidebarItem.tsx
> +                <Divider sx={{ '&.MuiDivider-fullWidth': { margin: 0 } }} />
По хорошему стилей в sx не должно быть. Сделать `SidebarItemTooltipDivider`.

2022-11-09 09:50 UTC, feerzlay commented on src/components/Sidebar/SidebarItem/SidebarItem.tsx
> +            <SidebarItemMenuItem className={clsx(classes.itemMenuItem)} onClick={onClick}>
Всем этим айтемам в тултипе необходимо прокидывать их пропс `component`. Иначе не кликабельные выходят. Может вообще спредить пропсы в каком-то виде.

2022-11-09 09:50 UTC, feerzlay commented on src/components/Sidebar/SidebarItem/SidebarItem.classes.ts
> +  itemChevron: string;
Не используется?

2022-11-11 11:27 UTC, va25j commented on src/components/Sidebar/SidebarToggle/SidebarToggle.tsx
> +            <SidebarToggleTooltipTitle className={clsx(classes.toggleTooltipTitle)} onMouseEnter={onCloseTooltip}>
точно, есть _disableInteractive_

2022-11-11 13:08 UTC, va25j commented on src/components/Sidebar/SidebarItem/SidebarItem.classes.ts
> +  itemChevron: string;
ага)

2022-11-15 09:17 UTC, feerzlay commented on src/components/Sidebar/SidebarItem/SidebarItem.types.ts
> +    /** Icon toggle for the item element. */
```suggestion
    /** Icon for the toggle button element. */
```

2022-11-15 09:17 UTC, feerzlay commented on src/components/Sidebar/SidebarItem/SidebarItem.tsx
> +    iconToggle,
Добавить дефолтное значение.

2022-11-15 09:17 UTC, feerzlay commented on src/components/Sidebar/SidebarItem/SidebarItem.tsx
> +const SidebarItemMenuItem = styled(MenuItem, {
slot и overridesResolver остались ещё старые.

2022-11-15 09:29 UTC, feerzlay requested changes

2022-11-15 09:29 UTC, feerzlay commented on src/components/Sidebar/SidebarItem/SidebarItem.tsx
> +  slot: 'TooltipItem',
```suggestion
  slot: 'TooltipDivider',
```
Видимо не там от айтема вписал.

2022-11-15 09:29 UTC, feerzlay commented on src/components/Sidebar/SidebarItem/SidebarItem.tsx
> +                <SidebarItemTooltipDivider />
Добавить className.

2022-11-15 09:29 UTC, feerzlay commented on src/hooks/useMenuAim/useMenuAim.ts
> + * @param isActive The other submenu row already active.
```suggestion
 * @param isActive Whether the other submenu row is already active.
```

2022-11-15 11:11 UTC, va25j commented on src/components/Sidebar/SidebarToggle/SidebarToggle.tsx
> +  '&[data-popper-placement*="right"] .MuiTooltip-tooltip': {
Да, тут это лишнее. Оставил только манипуляции с display, чтобы tooltip быстро скрывался и radius для arrow.

2022-11-16 08:14 UTC, feerzlay commented on src/components/Sidebar/Sidebar.stories.tsx
> +              onClick={() => console.log(`Projects`)}
Почему то этот обработчик срабатывает по клику на тоггл, а не на сам пункт меню.

2022-11-16 08:21 UTC, feerzlay commented on src/components/Sidebar/SidebarItem/SidebarItem.tsx
> +                    <IconChevronLeftMedium />
Сюда тоже `iconToggle` нужен.

2022-11-16 08:38 UTC, feerzlay commented on src/icons/IconChevronLeftMedium.tsx
> +export const IconChevronLeftMedium = (props: SvgIconProps) => {
Это точно Small, а не Medium.

2022-11-16 08:38 UTC, feerzlay commented on src/icons/IconChevronLeftLarge.tsx
> +export const IconChevronLeftLarge = (props: SvgIconProps) => {
А вот этот можно пока что Medium назвать.

2022-11-16 10:40 UTC, va25j commented on src/components/locale/index.ts
> +        labelHide: 'Collapse sidebar'
да, давай)

2022-11-18 10:33 UTC, merged