feat(Sidenav): add new component
Elonsoft/elonkit-react pull request #116
Opened 2022-10-12 13:19 UTC by va25j

2022-11-23 08:46 UTC, feerzlay requested changes

2022-11-23 08:46 UTC, feerzlay commented on src/components/Sidenav/Sidenav.tsx
> +                {React.cloneElement(child, { itemIndex })}
Для чего тут (и выше) `itemIndex` прокидывается?

2022-11-23 08:46 UTC, feerzlay commented on src/components/Sidenav/Sidenav.tsx
> +          {React.Children.map(children, (child: any, idx: number) => {
Убрать бы `any`.

2022-11-23 08:46 UTC, feerzlay commented on src/components/Sidenav/Sidenav.tsx
> +  const onKeyDown = (e: KeyboardEvent) => {
Перенести внутрь эффекта.

2022-11-23 08:46 UTC, feerzlay commented on src/components/Sidenav/Sidenav.tsx
> +  const [itemIndex, setIndex] = useState<string | null>(null);
Надо бы переименовать, так как сюда записывается не индекс, а айдишник, который строкойвой и там что угодно может быть. Как вариант:
```suggestion
  const [id, setId] = useState<string | null>(null);
```

2022-11-23 09:57 UTC, va25j commented on src/components/Sidenav/Sidenav.tsx
> +                {React.cloneElement(child, { itemIndex })}
лишнее))

2022-11-23 10:09 UTC, va25j commented on src/components/Sidenav/Sidenav.tsx
> +  const [itemIndex, setIndex] = useState<string | null>(null);
переименовал на _itemId_ , чтобы не было конфликта в имени с _id_ , который прилетает айтему через пропсы)

2022-11-29 11:23 UTC, feerzlay requested changes

2022-11-29 11:23 UTC, feerzlay commented on src/components/Sidenav/Sidenav.context.tsx
> +  /** Set is hover component. */
```suggestion
  /** Set the hover state. */
```

2022-11-29 11:23 UTC, feerzlay commented on src/components/Sidenav/Sidenav.context.tsx
> +  /** Set is id item. */
```suggestion
  /** Set the id of the selected element. */
```

2022-11-29 11:23 UTC, feerzlay commented on src/components/Sidenav/Sidenav.types.ts
> +  /** If `true`, the component is shown. */
Тоже не идеально, но лучше.
```suggestion
/** Whether the sidebar should be displayed. */
```

2022-11-29 11:23 UTC, feerzlay commented on src/components/Sidenav/SidenavItem/SidenavItem.tsx
> +            <SidenavItemTooltipTitle className={clsx(classes.tooltipTitle)} disablePadding>
Тут же тултип просто информационный, никаких кликабельных элементов не содержит. Тогда можно просто текст прокидывать, а стили и шрифт в `SidenavItemTooltip` задать.

2022-11-29 11:24 UTC, feerzlay commented
Удалить изображение аватара.

2022-11-29 13:22 UTC, feerzlay requested changes

2022-11-29 13:22 UTC, feerzlay commented on src/components/Sidenav/SidenavItem/SidenavItem.tsx
> +    filter: 'drop-shadow(0px 3px 6px rgba(0, 0, 0, 0.03)) drop-shadow(0px 8px 16px rgba(0, 0, 0, 0.07))',
По хорошему тень из токенов должна быть.

2022-11-29 13:22 UTC, feerzlay commented on src/components/Sidenav/SidenavItem/SidenavItem.classes.ts
> +  tooltipTitle: string;
Убрать теперь лишние два класса.

2022-12-07 14:26 UTC, merged