refactor: use class maps instead of hardcoded string
Elonsoft/elonkit-react pull request #126
Opened 2022-12-22 13:26 UTC by va25j

2022-12-22 14:44 UTC, feerzlay requested changes

2022-12-22 14:44 UTC, feerzlay commented on src/components/Sidenav/Sidenav.tsx
> +      target.className.toString().includes(`${sidebarMenuClasses.root}`) ||
Можно и без интерполяции.

2022-12-22 14:44 UTC, feerzlay commented on src/components/Table/TableCell/TableCell.tsx
> +      style.textContent = `* { cursor: col-resize !important; } .${tableCellClasses.resize}:after { display: none; }`;
Второе `:` потерялось.

2022-12-22 14:44 UTC, feerzlay commented on src/theming/mixins/listItem.ts
> +import { listItemTextClasses, touchRippleClasses } from '@mui/material';
`listItemTextClasses` можно тогда тоже из компонента импортировать.

2022-12-22 15:17 UTC, va25j commented on src/theming/mixins/listItem.ts
> +import { listItemTextClasses, touchRippleClasses } from '@mui/material';
тут тоже ListItemButton не импортит как в случае с _outlinedInputClasses_

2022-12-23 07:32 UTC, feerzlay approved these changes

2022-12-23 13:17 UTC, merged