feat(Breadcrumbs): add new component
Elonsoft/elonkit-react pull request #136
Opened 2023-01-30 16:14 UTC by va25j

2023-01-31 09:19 UTC, feerzlay requested changes

2023-01-31 09:19 UTC, feerzlay commented on src/components/Breadcrumbs/Breadcrumbs.tsx
> +                  {buttonMoreLabel}
Проверь стили крошки с иконкой, она по вертикали съехала.

2023-01-31 09:19 UTC, feerzlay commented on src/components/Breadcrumbs/Breadcrumbs.tsx
> +  padding: '0',
Убрать внешние отступы.

2023-01-31 09:19 UTC, feerzlay commented on src/components/Breadcrumbs/Breadcrumbs.tsx
> +  [`& .${breadcrumbClasses.root}:last-of-type`]: {
Это можно в Breadcrumb перенести.

2023-01-31 09:19 UTC, feerzlay commented on src/components/Breadcrumbs/Breadcrumb/Breadcrumb.tsx
> +const BreadcrumbContent = styled(Button, {
Для последней крошки нужно сворачивание в троеточие с минимальной шириной 40px.

2023-01-31 09:19 UTC, feerzlay commented on src/components/Breadcrumbs/Breadcrumbs.tsx
> +  ...theme.typography.caption
Еще размеры айтема надо поменять.

2023-01-31 09:19 UTC, feerzlay commented on src/components/Breadcrumbs/Breadcrumbs.tsx
> +                <Breadcrumb
Скорее всего на этой кнопке не должно быть микроразметки

2023-01-31 14:30 UTC, va25j commented on src/components/Breadcrumbs/Breadcrumbs.tsx
> +                <Breadcrumb
Да, точно)

2023-01-31 15:39 UTC, feerzlay requested changes

2023-01-31 15:39 UTC, feerzlay commented on src/icons/IconChevronRightSeparator.tsx
> +      <path d="M6 8L10 12L6 16" stroke={theme.palette.monoA.A500} strokeWidth="1.5" />
```suggestion
      <path d="M6 8L10 12L6 16" stroke="currentColor" strokeWidth="1.5" />
```

2023-01-31 15:39 UTC, feerzlay commented on src/components/Breadcrumbs/Breadcrumbs.types.ts
> +  /** Text for the button more label. */
```suggestion
  /** Text for the button more aria-label. */
```

2023-01-31 15:39 UTC, feerzlay commented on src/components/Breadcrumbs/Breadcrumbs.stories.mdx
> +    iconButtonMore: {
Скрыть еще `labelButtonMore`.

2023-01-31 15:39 UTC, feerzlay commented on src/components/Breadcrumbs/Breadcrumbs.tsx
> +  minHeight: '32px',
Еще горизонтальные внутренние отступы должны быть меньше.

2023-01-31 15:39 UTC, feerzlay commented on src/components/Breadcrumbs/Breadcrumb/Breadcrumb.tsx
> +const BreadcrumbSeperator = styled('div', {
Шеврон шире чем должен быть по дизайну (24 против 16).

2023-02-03 14:36 UTC, feerzlay requested changes

2023-02-03 14:36 UTC, feerzlay commented on src/components/Breadcrumbs/Breadcrumb/Breadcrumb.tsx
> +    name: 'ESidebarItem',
```suggestion
    name: 'ESBreadcrumb',
```

2023-02-03 14:39 UTC, feerzlay requested changes

2023-02-03 14:39 UTC, feerzlay commented on src/components/Breadcrumbs/Breadcrumbs.tsx
> +export const Breadcrumbs = (inProps: BreadcrumbsProps) => {
Добавить описание компонента (можно скопировать из mui).

2023-02-03 14:39 UTC, feerzlay commented on src/components/Breadcrumbs/Breadcrumb/Breadcrumb.types.ts
> +     * Whether the first breadcrumb should be shrink.
```suggestion
     * Whether the first breadcrumb should shrink.
```

2023-02-03 14:39 UTC, feerzlay commented on src/components/Breadcrumbs/Breadcrumb/Breadcrumb.types.ts
> +     * The breadcrumb position of the list.
```suggestion
     * The breadcrumb position in the list.
```

2023-02-28 14:31 UTC, feerzlay requested changes

2023-02-28 14:31 UTC, feerzlay commented on src/components/Breadcrumbs/Breadcrumb/Breadcrumb.tsx
> +  overridesResolver: (props, styles) => styles.root
Раз выше добавили, то и тут стоит `disabled` и `shouldFirstShrink` учесть.

2023-03-01 13:46 UTC, merged