feat(Spinner): add new component
Elonsoft/elonkit-react pull request #19
Opened 2021-08-23 10:29 UTC by meddvedev

2021-08-25 09:00 UTC, feerzlay requested changes

2021-08-30 09:12 UTC, feerzlay requested changes

2021-08-30 09:12 UTC, feerzlay commented on src/ui/Spinner/Spinner.stories.mdx
> +      </div>
Предложение как можно переименовать (с заделом на возможное расширение коллекции):
```
<SpinnerFadingRing />
<SpinnerFadingDots />
<SpinnerFadingBars />
<SpinnerRing />
<SpinnerDashRing />
<SpinnerFadingDoubleRing />
```

2021-08-30 10:51 UTC, meddvedev commented on src/ui/Spinner/Spinner.stories.mdx
> +`Spinner` is a component for express an unspecified wait time or display the length of a process. The animation works with CSS, not JavaScript.
Xd

2021-08-31 15:40 UTC, feerzlay requested changes

2021-08-31 15:40 UTC, feerzlay commented on src/ui/Spinner/index.ts
> +export { SpinnerFadingRing } from './SpinnerFadingRing';
Раз их стало так много то предлагаю разложить по поддиректориям, можно посмотреть пример в ветке `feature/gallery`.

2021-08-31 15:40 UTC, feerzlay commented on src/ui/Spinner/Spinner.types.ts
> +export interface SpinnerFadingRingProps extends SpinnerBaseProps<SpinnerFadingRingClasses> {}
Что это тут забыло? =)

2021-08-31 15:40 UTC, feerzlay commented on src/ui/Spinner/Spinner.stories.mdx
> +        <SpinnerFadingDoubleRing {...args} />
Можно поставить после `SpinnerFadingRing`, они же похожи

2021-08-31 15:40 UTC, feerzlay commented on src/ui/Spinner/Spinner.stories.mdx
> +Example
Эта демка выглядит лишней, все уже вполне покрыли предыдущими двумя.

2021-08-31 15:40 UTC, feerzlay commented on src/ui/Spinner/Spinner.stories.mdx
> +<ul>
Тут расставить порядок как в сайдбаре.

2021-08-31 15:40 UTC, feerzlay commented on src/ui/Spinner/Spinner.stories.mdx
> +<p>
Отсюда только `dashEase` новое, остальное уже поняли раньше =)
Может или чисто один этот спиннер оставить с настройками анимации, или как-то добавить dashEase в первую демку

2021-08-31 15:40 UTC, feerzlay commented on src/overrides.d.ts
> +    ESSpinnerFadingRing: SpinnerFadingRingProps;
Тут бы тоже в алфавитном порядке раскидать

2021-08-31 15:40 UTC, feerzlay commented on src/ui/Spinner/SpinnerDashRing.types.ts
> +  dashEase?: string;
Задокументировать

2021-08-31 15:40 UTC, feerzlay commented on src/ui/Spinner/SpinnerHooks.ts
> +import { useTheme } from '@material-ui/core/styles';
Этот файл назвать как и хук - `useSpinnerColor.ts`

2021-08-31 15:40 UTC, feerzlay commented on src/ui/Spinner/Spinner.types.ts
> +export type ColorType = 'primary' | 'secondary' | 'monoA.500';
```suggestion
export type SpinnerColor = 'inherit' | 'primary' | 'secondary' | 'monoA';
```

2021-08-31 15:40 UTC, feerzlay commented on src/ui/Spinner/SpinnerHooks.ts
> +    return colors.length === 2 ? theme.palette[colors[0]][colors[1]] : theme.palette[colors[0]][300];
Возможность произвольный оттенок выбирать? Просто при том что такое есть только в `monoA` да и то по типезации мы не можем передать ничего другого кроме 500, то не проще ли просто пару `if`'ов воткнуть?

2021-08-31 15:40 UTC, feerzlay commented on src/ui/Spinner/SpinnerFadingDoubleRing.classes.ts
> +export const SpinnerFadingDoubleRingClasses: SpinnerFadingDoubleRingClasses = generateUtilityClasses(
Эта константа должна с маленькой буквы начинаться, иначе совпадает с типом.

2021-08-31 15:40 UTC, feerzlay commented on src/ui/Spinner/SpinnerUtils.ts
> +import { keyframes, css } from '@material-ui/system';
Этот файл я бы назвал `Spinner.animations.ts`

2021-09-01 09:38 UTC, feerzlay requested changes

2021-09-01 09:38 UTC, feerzlay commented on src/ui/Spinner/Spinner.stories.mdx
> +    dashEase: {
Ему бы еще тип и значение по умолчанию прописать, чтобы как в `ease` было.

2021-09-01 09:38 UTC, feerzlay commented on src/ui/Spinner/Spinner.stories.mdx
> +      <div style={{display: 'flex', gap: '24px', alignItems: 'baseline'}}>
Тут бы через `grid` сделать, а то у `gap` для `flex` еще не идеальная поддержка.

2021-09-01 09:38 UTC, feerzlay commented on src/ui/Spinner/SpinnerDashRing/SpinnerDashRing.tsx
> +    root: ['root'],
Сейчас только задумался, может стоит для root сюда и в overridesResolver добавить `color`? Чтобы в случае чего можно было оттенок заменить или селекторы для спиннеров определенного цвета писать в приложении.

2021-09-01 09:38 UTC, feerzlay commented on src/ui/Spinner/SpinnerFadingDoubleRing/SpinnerFadingDoubleRing.tsx
> +        <clipPath id="clip1">
А не будет проблем с айдишником когда два одинаковых спиннера на странице?

2021-09-01 09:38 UTC, feerzlay commented on src/ui/Spinner/SpinnerFadingRing/SpinnerFadingRing.tsx
> +        <clipPath id="clip2">
Тот же вопрос по айдишнику.

2021-09-01 09:38 UTC, feerzlay commented on src/ui/Spinner/Spinner.spec.tsx
> +  it('Should display SpinnerFadingRing', async () => {
Ага, от вот этих тестов про `Should display`с поиcком `svg` смысла особого нет =) На их месте могли бы быть снэпшоты, но мы их не делаем.

2021-09-01 09:38 UTC, feerzlay commented on src/ui/Spinner/Spinner.spec.tsx
> +  it('Should display Spinner with primary color', async () => {
А вот этот в принципе имеет смысл, но только:
- Неплохо бы было все цвета из `SpinnerColor` покрывать 
- Тест на `toBeInTheDocument` не нужен
- `getByTestId` вместо `querySelector`
- Цвет для сравнения не хардкодить, а импортировать объект палитры и брать из него
- Сделать подобные тесты для всех спиннеров

Местами можно попробовать избавиться от дублирования с помощью циклов - заводим массив компонентов и массив цветов (объекты `key: value`), делаем вложенный цикл с `it` внутри

2021-09-01 09:38 UTC, feerzlay commented on src/ui/Spinner/Spinner.spec.tsx
> +describe('SpinnerFadingRing', () => {
Еще можно сделать тесты на `size`

2021-09-01 15:39 UTC, feerzlay requested changes

2021-09-01 15:39 UTC, feerzlay commented on src/ui/Spinner/SpinnerFadingRing/SpinnerFadingRing.classes.ts
> +  'ESSpinnerFadingRingClassKey',
```suggestion
  'ESSpinnerFadingRing',
```

2021-09-01 15:39 UTC, feerzlay commented on src/ui/Spinner/SpinnerFadingRing/SpinnerFadingRing.classes.ts
> +export function getSpinnerFadingRingClassKeyUtilityClass(slot: string): string {
```suggestion
export function getSpinnerFadingRingUtilityClass(slot: string): string {
```

2021-09-01 15:39 UTC, feerzlay commented on src/ui/Spinner/SpinnerFadingRing/SpinnerFadingRing.classes.ts
> +  return generateUtilityClass('ESSpinnerFadingRingClassKey', slot);
```suggestion
  return generateUtilityClass('ESSpinnerFadingRing', slot);
```

2021-09-01 15:39 UTC, feerzlay commented on src/ui/Spinner/SpinnerDashRing/SpinnerDashRing.classes.ts
> +  return generateUtilityClass('ESSpinnerRing', slot);
```suggestion
  return generateUtilityClass('ESSpinnerDashRing', slot);
```

2021-09-01 15:39 UTC, feerzlay commented on src/ui/Spinner/SpinnerDashRing/SpinnerDashRing.classes.ts
> +export const spinnerDashRingClasses: SpinnerDashRingClasses = generateUtilityClasses('ESSpinnerRing', ['root', 'svg']);
```suggestion
export const spinnerDashRingClasses: SpinnerDashRingClasses = generateUtilityClasses('ESSpinnerDashRing', ['root', 'svg']);
```

2021-09-01 15:39 UTC, feerzlay commented on src/ui/Spinner/SpinnerDashRing/SpinnerDashRing.tsx
> +    root: ['root', color],
С этим `color` немного криво вышло, забыл что тут лежит уже итоговое значение цвета, в итоге получаем `ESSpinnerDashRing-#4AB6BD` вместо `ESSpinnerDashRing-primary`. Предлагаю в `styleProps` держать как исходное значение из пропсов (`color`), так и значение цвета из темы (`spinnerColor`).

2021-09-01 15:39 UTC, feerzlay commented on src/ui/Spinner/SpinnerFadingBars/SpinnerFadingBars.classes.ts
> +export type SpinnerFadingBarsClasses = {
Раз добавляем `color` в utilityClasses и overrides то и в эти интерфейсы надо добавить inherit, primary, secondary, monoA.

```
/** Styles applied to the root element if `color='primary'`. */
primary: string;
```

Кстати, заодно можно эту пустую строку убрать, когда коммент однострочный то оно не особо сливается =)

2021-09-01 15:39 UTC, feerzlay commented on src/ui/Spinner/Spinner.spec.tsx
> +const makeComponentsArray = () => {
Тут лучше явно описать объект (дальше станет понятно зачем):
```
const COMPONENTS = {
  'SpinnerDashRing': SpinnerDahsRing,
  //...
}
```

2021-09-01 15:39 UTC, feerzlay commented on src/ui/Spinner/Spinner.spec.tsx
> +const COLORS = [
Блин, не подумав про массив написал =)
Тут лучше объектом:
```
const COLORS = {
  inherit: 'currentColor',
  primary: palettes.light.primary[300],
  // ...
}
```

2021-09-01 15:39 UTC, feerzlay commented on src/ui/Spinner/Spinner.spec.tsx
> +  components.forEach((Component, i) => {
- По цветам тоже нужна итерация
- Название теста генерим через шаблонные строки

```
Object.keys(COMPONENTS).forEach(component => {
  const Component = COMPONENTS[component];
 
  Object.keys(COLORS).forEach(color => {
    it(`Should display ${component} with ${color} color`, async () => {
      render(<Component color={color} />);
      expect(screen.getByTestId(color)).toHaveStyle({ color: COLORS[color] }); // Как-то так же раньше было? А то тест без `.toЧтоТо` это и не тест вовсе.
    })
  });

  // Тут можно вставить тест на `size`
});
```

2021-09-01 15:39 UTC, feerzlay commented on src/ui/Spinner/Spinner.stories.mdx
> +       table: {
Мелочь на последок - отступ сдвинут на один пробел :D

2021-09-03 15:51 UTC, merged