feat(PageHGroupHeading): display a tooltip when the title goes into ellipsis
Elonsoft/elonkit-react pull request #227
Opened 2024-02-15 11:53 UTC by AlbetItrum

2024-02-15 14:41 UTC, feerzlay requested changes

2024-02-15 14:41 UTC, feerzlay commented on src/components/PageHGroup/PageHGroupHeading/PageHGroupHeading.tsx
> +const PageHGroupHeadingRoot = styled('span', {
```suggestion
const PageHGroupHeadingRoot = styled('h1', {
```

2024-02-15 14:41 UTC, feerzlay commented on src/components/PageHGroup/PageHGroupHeading/PageHGroupHeading.tsx
> +  }
Стили можно убрать, оставить только сам styled компонент.

2024-02-15 14:41 UTC, feerzlay commented on src/components/PageHGroup/PageHGroupHeading/PageHGroupHeading.tsx
> +      title={<Typography variant="caption">{children || false}</Typography>}
Сделать пропсы тултипа как в компоненте `TableText`.

2024-02-16 11:02 UTC, AlbetItrum commented on src/components/PageHGroup/PageHGroupHeading/PageHGroupHeading.tsx
> +  }
Просто оставить компонент без стилей? 
```
const PageHGroupHeadingTooltip = ({ className, ...props }: TooltipEllipsisProps) => (
  <TooltipEllipsis {...props} classes={{ popper: className }} />
);
```

2024-03-04 07:36 UTC, merged