feat(Badge): add new component
Elonsoft/elonkit-react pull request #230
Opened 2024-02-19 11:32 UTC by AlbetItrum

2024-02-19 11:53 UTC, feerzlay requested changes

2024-02-19 11:53 UTC, feerzlay commented on src/components/Badge/Badge.tsx
> +    <BadgeRoot ownerState={ownerState} onClick={onClick}>
Добавить utility classes для цвета и размера.

2024-02-19 11:53 UTC, feerzlay commented on src/components/Badge/Badge.tsx
> +  color: getPath<string>(theme, `palette.${color}`) || (color as string),
После добавления utility classes цвет надо будет сделать через обычные селекторы, см. как в компоненте Alert.

2024-02-19 11:53 UTC, feerzlay commented on src/components/Badge/Badge.types.ts
> +  onClick?: (e: React.MouseEvent<HTMLButtonElement, MouseEvent>) => void;
Надо сделать чтобы этот (и потенциально другие пропсы) автоматом наследовались от элемента `button`. По сути нужно сделать типизацию (и прокидывание пропсов) как в компоненте Link.

2024-02-19 11:53 UTC, feerzlay commented on src/components/Badge/Badge.tsx
> +  width: '100%',
Это всё уже есть в `ButtonBase` через риппл. Надо только немного подогнать стили у можно перекрашивать потом через миксин и просто стилями (см. CalendarButton и theming/components/button.ts):
```
    [`& .${touchRippleClasses.rippleVisible}`]: {
      animationName: `${enterKeyframe} !important`,
      opacity: '1 !important'
    },
```

2024-02-19 11:53 UTC, feerzlay commented on src/components/Badge/index.ts
> +export { BadgeProps } from './Badge.types';
Ещё добавить экспорт компонента в components/index.ts и типизацию для темы в overrides.d.ts (там в трех интерфейса его добавить, по аналогии с другими компонентами).

2024-02-19 11:53 UTC, feerzlay commented on src/components/Badge/Badge.types.ts
> +  value?: number;
Я бы сделал прокидывание содержимого через `children` и без всяких ограничений по `maxValue` (пусть жтим приложение занимается, если нужно)

2024-02-19 11:53 UTC, feerzlay commented on src/components/Badge/Badge.types.ts
> +  size?: number;
Для цвета и размера вот такую типизацию стоит сделать:
https://github.com/Elonsoft/elonkit-react/pull/213/files#diff-62ab67fa6f1df5fdea16ca8016b47769d6de794753711a345838f2dea6cb569aR35

Чтобы при необходимости на проекте её можно было расширить и добавить свой цвет/размер.

2024-02-19 11:53 UTC, feerzlay commented on src/components/Badge/Badge.types.ts
> +  backgroundColor?: TypographyProps['color'];
Не нужен, всё от `color` идет, и цвет текста и фон.

2024-02-19 11:53 UTC, feerzlay commented on src/components/Badge/Badge.types.ts
> +  variant?: variantType;
Получается надо оставить только `color` с типизацией похожей на этот пропс.

2024-02-26 08:44 UTC, feerzlay requested changes

2024-02-26 08:44 UTC, feerzlay commented on src/components/Badge/Badge.tsx
> +    return [styles.root, styles[variant], styles[`${variant}${capitalize(color || severity)}`]];
Копипастнул, но под наш компонент вообще не подстроил =)
```suggestion
    return [styles.root, styles[`colors${capitalize(color)}`], styles[`size${size}`]];
```

2024-02-26 09:32 UTC, AlbetItrum commented on src/components/Badge/Badge.classes.ts
> +  colorMonoA: string;
все цвета добавил, проверил -  есть вопрос с monoB: цвета отображаются некорректно как мне кажется. Можешь посмотреть?

2024-02-28 07:33 UTC, feerzlay requested changes

2024-02-28 07:33 UTC, feerzlay commented on src/components/Badge/Badge.stories.tsx
> +        <Badge {...args}></Badge>
Оставить только `Badge`, без оберток.

2024-06-04 13:38 UTC, feerzlay commented on packages/react/src/components/Badge/Badge.tsx
> +  fontFamily: 'Arial',
```suggestion
```

2024-06-04 13:38 UTC, feerzlay commented on packages/react/src/components/Badge/Badge.stories.tsx
> +    references: ['Badge']
Добавить `Badge.api.mdx`

2024-06-04 13:39 UTC, feerzlay commented on package.json
> +  "dependencies": {
Удалить и откатить package-lock

2024-06-11 11:40 UTC, merged