feat(Pagination): add new component
Elonsoft/elonkit-react pull request #36
Opened 2021-10-18 15:11 UTC by va25j

2021-11-11 15:07 UTC, feerzlay requested changes

2021-11-11 15:07 UTC, feerzlay commented on src/ui/Pagination/PaginationPages/PaginationPages.tsx
> +    if (event.key === 'Enter') {
Добавить проверку на непустой инпут.

2021-11-11 15:07 UTC, feerzlay commented on src/ui/Pagination/Pagination.spec.tsx
> +    fireEvent.change(paginationPagesTextField, { target: { value: 'One' } });
Сделать цепочку:
- Ввели цифру через `fireEvent.keypress`
- Проверили что в инпуте теперь цифра
- Ввели букву через `fireEvent.keypress`
- Проверили что в инпуте все еще одна цифра

2021-11-16 14:57 UTC, va25j commented on src/ui/Pagination/PaginationRange/PaginationRange.tsx
> +        {(page - 1) * options[selectedIndex] + (count ? 1 : 0)} &mdash;
+

2021-11-24 14:12 UTC, feerzlay requested changes

2021-11-24 14:12 UTC, feerzlay commented on src/ui/Pagination/PaginationPages/PaginationPages.classes.ts
> +  textField: string;
```suggestion
  input: string;
```

2021-11-24 14:12 UTC, feerzlay commented on src/ui/Pagination/PaginationPages/PaginationPages.tsx
> +  slot: 'Input',
```suggestion
  slot: 'TextField',
```

2021-11-24 14:12 UTC, feerzlay commented on src/ui/Pagination/PaginationPages/PaginationPages.tsx
> +  overridesResolver: (props, styles) => styles.root
```suggestion
  overridesResolver: (props, styles) => styles.textField
```

2021-11-24 14:12 UTC, feerzlay commented on src/ui/Pagination/PaginationPages/PaginationPages.tsx
> +const PaginationRoot = styled(Pagination, {
```suggestion
const PaginationPagesPagination = styled(Pagination, {
```

2021-11-24 14:12 UTC, feerzlay commented on src/ui/Pagination/PaginationPages/PaginationPages.tsx
> +const PaginationItemRoot = styled(PaginationItem, {
```suggestion
const PaginationPagesPaginationItem = styled(PaginationItem, {
```

2021-11-24 14:12 UTC, feerzlay commented on src/ui/Pagination/PaginationPages/PaginationPages.tsx
> +  overridesResolver: (props, styles) => styles.root
```suggestion
  overridesResolver: (props, styles) => styles.paginationItem
```

2021-11-24 14:12 UTC, feerzlay commented on src/ui/Pagination/PaginationPages/PaginationPages.tsx
> +  overridesResolver: (props, styles) => styles.root
```suggestion
  overridesResolver: (props, styles) => styles.pagination
```

2021-11-30 14:32 UTC, feerzlay requested changes

2021-11-30 14:32 UTC, feerzlay commented on src/ui/Pagination/PaginationPages/PaginationPages.types.ts
> +  regex?: RegExp;
О, а когда этот пропс успел повиться? Он в общем-то не нужен.

2021-11-30 14:32 UTC, feerzlay commented on src/ui/Pagination/PaginationPages/PaginationPages.classes.ts
> +  input: string;
Извиняюсь, запустался немного. Тут должно быть так же как и в компоненте - `textField`.

2021-12-01 09:18 UTC, feerzlay approved these changes

2021-12-03 12:19 UTC, merged