feat(Switch): add new component
Elonsoft/elonkit-react pull request #65
Opened 2022-03-30 12:07 UTC by meddvedev

2022-03-30 12:49 UTC, feerzlay requested changes

2022-03-30 12:49 UTC, feerzlay commented on src/overrides.d.ts
> +import { ISwitchProps, SwitchClassKey } from './components';
Дополнить путь.

2022-03-30 12:49 UTC, feerzlay commented on src/components/Switch/Switch.types.ts
> +export interface ISwitchProps {
```suggestion
export interface SwitchProps {
```

2022-03-30 12:49 UTC, feerzlay commented on src/components/Switch/Switch.stories.mdx
> +Sssssssss
Sssssssss

2022-03-30 12:49 UTC, feerzlay commented on src/hooks/useControlled/useControlled.ts
> +export const useControlled = <T>(defaultValue?: T, controlled?: T): [T | undefined, (value: T) => void] => {
Хук тогда тоже экспортировать и добавить документацияю.

2022-03-30 12:49 UTC, feerzlay commented on src/components/Switch/Switch.classes.ts
> +export type SwitchClasses = {
Нужно будет добавить классы с размерами.

2022-03-30 12:49 UTC, feerzlay commented on src/components/Switch/Switch.types.ts
> +  color?: 'primary' | 'secondary' | 'error' | 'info' | 'success' | 'warning';
Нужна ли эта возможность? В дизайне не прорисованно. И там secondary =)

2022-03-31 19:15 UTC, meddvedev commented on src/components/Switch/Switch.tsx
> +  const onKeyDown = (e: React.KeyboardEvent<HTMLInputElement>) => {
Добавить проверку keyCode

2022-04-01 08:07 UTC, feerzlay requested changes

2022-04-01 08:07 UTC, feerzlay commented on src/components/Switch/Switch.tsx
> +        backgroundColor: alpha(theme.palette[color].main, theme.palette.action.hoverOpacity),
Использовать `A50`

2022-04-01 08:07 UTC, feerzlay commented on src/components/Switch/Switch.tsx
> +  const tabIndex: any = { tabIndex: null };
`-1` не работает? И кстати зачем спредом делать а не написать сразу в пропсах?

2022-04-01 08:07 UTC, feerzlay commented on src/components/Switch/Switch.types.ts
> +  /** If 'button', hitting enter will toggle the switch. */
Указать `@default`

2022-04-01 08:07 UTC, feerzlay commented on src/components/Switch/Switch.types.ts
> +  /** Set component size */
```suggestion
  /** The size of the component. */
```
И указать `@default`

2022-04-01 11:22 UTC, feerzlay commented on src/components/Switch/Switch.tsx
> +    return [styles.root, styles[disabled], styles[checked], styles[size]];
```suggestion
    return [styles.root, disabled && styles.disabled, checked && styles.checked, styles[size]];
```

2022-04-06 14:40 UTC, merged