feat(AvatarGroup): add new component
Elonsoft/elonkit-react pull request #94
Opened 2022-05-17 09:01 UTC by meddvedev

2022-05-18 07:29 UTC, feerzlay requested changes

2022-05-18 07:29 UTC, feerzlay commented on src/theming/typography/typography.ts
> +    miniM: {
`mini1` это и есть `miniM`

2022-05-18 07:29 UTC, feerzlay commented on src/components/AvatarGroup/AvatarGroup.stories.mdx
> +        <Avatar sizes={args.sizes} alt="Remy Sharp" src="https://mui.com/static/images/avatar/1.jpg" />
Починить возможность выбора размера аватара и сделать его в группе контролов `AvatarProps`.

2022-05-18 07:29 UTC, feerzlay commented on src/components/AvatarGroup/AvatarGroup.stories.mdx
> +....
Добавить описание.

2022-05-18 07:29 UTC, feerzlay commented on src/components/AvatarGroup/AvatarGroup.tsx
> +        <AvatarGroupAvatar className={clsx(classes.extraElement, classes.avatar)}>
Убрать.

2022-05-26 09:00 UTC, meddvedev commented on src/components/AvatarGroup/AvatarGroup.utils.ts
> +
В целом можно детектить браузеры только через css запросы, но хз как лучше

2022-05-31 15:06 UTC, feerzlay requested changes

2022-05-31 15:06 UTC, feerzlay commented on src/components/AvatarGroup/AvatarGroup.tsx
> +          className: clsx(child.props.className, classes.avatar)
Может ну его, отдельно `classes.avatar` прокидывать, если аватары нужно застилизовать то это можно сделать отдельно перед их прокидыванием в `AvatarGroup`.

2022-06-02 09:05 UTC, feerzlay requested changes

2022-06-08 08:15 UTC, feerzlay approved these changes

2022-06-08 09:09 UTC, merged